MonitoraSUS/Controllers/MonitorarPacienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Model;
using Model.ViewModel;
using Util;
using Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace MonitoraSUS.Controllers
{
	[Authorize(Roles = "GESTOR, SECRETARIO")]
	public class MonitorarPacienteController : Controller
	{
		private readonly IVirusBacteriaService _virusBacteriaContext;
		private readonly IPessoaService _pessoaContext;
		private readonly ISituacaoVirusBacteriaService _situacaoPessoaContext;
		private readonly IPessoaTrabalhaEstadoService _pessoaTrabalhaEstadoContext;
		private readonly IPessoaTrabalhaMunicipioService _pessoaTrabalhaMunicipioContext;
		private readonly IExameService _exameContext;
		private readonly IMunicipioService _municicpioContext;
		private readonly IEstadoService _estadoContext;
		private readonly IEmpresaExameService _empresaExameContext;
		private readonly IInternacaoService _internacaoContext;
		private readonly IAreaAtuacaoService _areaAtuacaoContext;
		private readonly IUsuarioService _usuarioContext;
		private readonly IConfiguration _configuration;


		public MonitorarPacienteController(IVirusBacteriaService virusBacteriaContext,
							   IPessoaService pessoaContext,
							   IExameService exameContext,
							   IConfiguration configuration,
							   ISituacaoVirusBacteriaService situacaoPessoaContext,
							   IPessoaTrabalhaEstadoService pessoaTrabalhaEstado,
							   IPessoaTrabalhaMunicipioService pessoaTrabalhaMunicipioContext,
							   IMunicipioService municicpioContext,
							   IEstadoService estadoContext,
							   IInternacaoService internacaoContext,
							   IEmpresaExameService empresaExameContext,
							   IAreaAtuacaoService areaAtuacaoContext,
							   IUsuarioService usuarioContext)
		{
			_virusBacteriaContext = virusBacteriaContext;
			_pessoaContext = pessoaContext;
			_situacaoPessoaContext = situacaoPessoaContext;
			_pessoaTrabalhaEstadoContext = pessoaTrabalhaEstado;
			_pessoaTrabalhaMunicipioContext = pessoaTrabalhaMunicipioContext;
			_exameContext = exameContext;
			_municicpioContext = municicpioContext;
			_estadoContext = estadoContext;
			_internacaoContext = internacaoContext;
			_configuration = configuration;
			_empresaExameContext = empresaExameContext;
			_areaAtuacaoContext = areaAtuacaoContext;
			_usuarioContext = usuarioContext;
		}

		/* O formulário só enviava os campos vazios.
         * Essa solução com a lista de parâmetros extensa é provisória.*/
		public IActionResult Index(DateTime DataInicial, DateTime DataFinal, string Pesquisa,
									   string Resultado, int VirusBacteria)
		{
			var virus = _virusBacteriaContext.GetAll();
			ViewBag.VirusBacteria = new SelectList(virus, "IdVirusBacteria", "Nome");
			ViewBag.AreaAtuacao = new SelectList(_areaAtuacaoContext.GetAll(), "IdAreaAtuacao", "Descricao");
			if (VirusBacteria == 0)
				VirusBacteria = virus.First().IdVirusBacteria;
			int diasRecuperacao = virus.Where(v => v.IdVirusBacteria == VirusBacteria).First().DiasRecuperacao;

			var pesquisa = new PesquisaPacienteViewModel
			{
				Exames = new List<MonitoraPacienteViewModel>(),
				Resultado = Resultado,
				DataFinal = DataFinal.Equals(DateTime.MinValue) ? DateTime.Now : DataFinal,
				DataInicial = DataInicial.Equals(DateTime.MinValue) ? DateTime.Now.AddDays(-diasRecuperacao) : DataInicial,
				Pesquisa = Pesquisa,
				VirusBacteria = VirusBacteria,
			};

			return View(GetAllPacientesViewModel(pesquisa));
		}


		public IActionResult Edit(int idPaciente, int IdVirusBacteria)
		{
			ViewBag.googleKey = _configuration["GOOGLE_KEY"];
			ViewBag.Empresas = _empresaExameContext.GetHospitais();

			return View(GetPacienteViewModel(idPaciente, IdVirusBacteria));
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(MonitoraPacienteViewModel monitoraPaciente)
		{
			ViewBag.googleKey = _configuration["GOOGLE_KEY"];
			ViewBag.Empresas = _empresaExameContext.GetAll();

			/*
             * Fazendo validações no cpf
             */
			monitoraPaciente.Paciente.Cpf = monitoraPaciente.Paciente.Cpf ?? "";
			if (Methods.SoContemNumeros(monitoraPaciente.Paciente.Cpf) && !monitoraPaciente.Paciente.Cpf.Equals(""))
			{
				if (!Methods.ValidarCpf(monitoraPaciente.Paciente.Cpf))
				{
					TempData["resultadoPesquisa"] = "Esse esse cpf não é válido!";
					return View(GetPacienteViewModel(monitoraPaciente.Paciente.Idpessoa, monitoraPaciente.VirusBacteria.IdVirusBacteria));
				}
			}
			var usuarioDuplicado = _pessoaContext.GetByCpf(monitoraPaciente.Paciente.Cpf);
			if (usuarioDuplicado != null)
			{
				if (!(usuarioDuplicado.Idpessoa == monitoraPaciente.Paciente.Idpessoa))
				{
					TempData["resultadoPesquisa"] = "Já existe outro paciente com esse CPF/RG, tente novamente!";
					return View(GetPacienteViewModel(monitoraPaciente.Paciente.Idpessoa, monitoraPaciente.VirusBacteria.IdVirusBacteria));
				}
			}

			try
			{
				UpdateSituacaoPessoaVirusBacteria(monitoraPaciente);
				UpdatePaciente(monitoraPaciente);
			}
			catch
			{
				TempData["mensagemErro"] = "Houve um problema ao atualizar informações do paciente, por favor, tente novamente!";
				return View(GetPacienteViewModel(monitoraPaciente.Paciente.Idpessoa, monitoraPaciente.VirusBacteria.IdVirusBacteria));
			}

			TempData["mensagemSucesso"] = "Monitoramento realizado com sucesso!";
			return View(GetPacienteViewModel(monitoraPaciente.Paciente.Idpessoa, monitoraPaciente.VirusBacteria.IdVirusBacteria));
		}


		public bool UpdateSituacaoPessoaVirusBacteria(MonitoraPacienteViewModel monitoraPaciente)
		{
			var usuario = _usuarioContext.RetornLoggedUser((ClaimsIdentity)User.Identity);

			var situacaoModel = _situacaoPessoaContext.GetById(monitoraPaciente.Paciente.Idpessoa, monitoraPaciente.VirusBacteria.IdVirusBacteria);
			situacaoModel.IdGestor = usuario.UsuarioModel.IdPessoa;
			situacaoModel.DataUltimoMonitoramento = DateTime.Now;
			situacaoModel.Descricao = monitoraPaciente.Descricao;
			return _situacaoPessoaContext.Update(situacaoModel);
		}

		public bool UpdatePaciente(MonitoraPacienteViewModel monitoraPaciente)
		{
			return _pessoaContext.Update(monitoraPaciente.Paciente, true) != null ? true : false;
		}

		public MonitoraPacienteViewModel GetPacienteViewModel(int idPaciente, int IdVirusBacteria)
		{
			var situacao = _situacaoPessoaContext.GetById(idPaciente, IdVirusBacteria);
			var pessoa = _pessoaContext.GetById(idPaciente);
			
			var internacoes  = _internacaoContext.GetByIdPaciente(pessoa.Idpessoa);
			for (int i = 0; i < internacoes.Count; i++)
			{
				var empresa = _empresaExameContext.GetById(internacoes[i].IdEmpresa);
				internacoes[i].NomeEmpresa = empresa.Nome;
				internacoes[i].IdEmpresa = empresa.Id;
			}

			var monitora = new MonitoraPacienteViewModel
			{
				Paciente = pessoa,
				Descricao = situacao.Descricao,
				VirusBacteria = _virusBacteriaContext.GetById(situacao.IdVirusBacteria),
				ExamesPaciente = _exameContext.GetByIdPaciente(pessoa.Idpessoa),
				Internacoes = internacoes
			};
			monitora.UltimoResultado = GetUltimoResultadoExame(monitora.ExamesPaciente);
			return monitora;
		}


		public PesquisaPacienteViewModel GetAllPacientesViewModel(PesquisaPacienteViewModel pesquisa)
		{
			var usuario = _usuarioContext.RetornLoggedUser((ClaimsIdentity)User.Identity);
			var pessoaTrabalhaMunicipio = _pessoaTrabalhaMunicipioContext.GetByIdPessoa(usuario.UsuarioModel.IdPessoa);
			var pessoaTrabalhaEstado = _pessoaTrabalhaEstadoContext.GetByIdPessoa(usuario.UsuarioModel.IdPessoa);

			if (usuario.RoleUsuario.Equals("GESTOR") || usuario.RoleUsuario.Equals("SECRETARIO"))
			{
				if (pessoaTrabalhaMunicipio != null)
				{
					var municicpio = _municicpioContext.GetById(pessoaTrabalhaMunicipio.IdMunicipio);
					var estado = _estadoContext.GetByCodUf(Convert.ToInt32(municicpio.Uf));
					pesquisa.Exames = _exameContext.GetByCidadeResidenciaPaciente(municicpio.Nome, estado.Uf.ToUpper(), pesquisa.VirusBacteria, pesquisa.DataInicial, pesquisa.DataFinal).ToList();
				}
				if (pessoaTrabalhaEstado != null)
				{
					if (pessoaTrabalhaEstado.IdEmpresaExame != EmpresaExameModel.EMPRESA_ESTADO_MUNICIPIO)
					{
						var empresa = _empresaExameContext.GetById(pessoaTrabalhaEstado.IdEmpresaExame);
						if (empresa.FazMonitoramento)
						{
							pesquisa.Exames = _exameContext.GetByHospital(pessoaTrabalhaEstado.IdEmpresaExame, pesquisa.VirusBacteria, pesquisa.DataInicial, pesquisa.DataFinal).ToList();
						}
						else
						{
							TempData["mensagemAviso"] = "Essa Funcionalidade Não está Disponível Para Organizações Privadas!";
							return new PesquisaPacienteViewModel();
						}
					}
					else
					{
						var estado = _estadoContext.GetById(pessoaTrabalhaEstado.IdEstado);
						pesquisa.Exames = _exameContext.GetByEstadoResidenciaPaciente(estado.Uf.ToUpper(), pesquisa.VirusBacteria, pesquisa.DataInicial, pesquisa.DataFinal).ToList();
					}
				}
			}

			/*
             * 2º Filtro - filtrando ViewModel por nome/cpf, resultado e exame
             */
			pesquisa.Pesquisa = pesquisa.Pesquisa ?? "";
			pesquisa.Resultado = pesquisa.Resultado ?? "";

			if (!pesquisa.Pesquisa.Equals(""))
				if (Methods.SoContemLetras(pesquisa.Pesquisa))
					pesquisa.Exames = pesquisa.Exames.Where(paciente => paciente.Paciente.Nome.ToUpper().Contains(pesquisa.Pesquisa.ToUpper())).ToList();
				else
					pesquisa.Exames = pesquisa.Exames.Where(paciente => paciente.Paciente.Cpf.ToUpper().Contains(pesquisa.Pesquisa.ToUpper())).ToList();

			if (!pesquisa.Resultado.Equals("") && !pesquisa.Resultado.Equals("Todas as Opçoes"))
				pesquisa.Exames = pesquisa.Exames.Where(paciente => paciente.UltimoResultado.ToUpper().Equals(pesquisa.Resultado.ToUpper())).ToList();

			pesquisa.Exames = pesquisa.Exames.OrderByDescending(ex => ex.DataExame).ToList();

MonitoraSUS/Views/MonitorarPaciente/Index.cshtml
@model Model.ViewModel.PesquisaPacienteViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-md-12">
			<div class="card card-content">
				<div class="card-header bg-transparent">
					<div class="row align-items-center">

						<div class="col">
							<h5 class="card-title text-muted mb-0">MonitoraSUS</h5>
							<h5 class="h3 mb-0">Monitoramento de Pacientes</h5>
						</div>
						<div class="col text-right">
							<!--a class="btn btn-success" asp-action="Create">Novo Exame</!--a-->
							<a class="btn btn-default" asp-controller="Home" asp-action="Index"> <i class="fas fa-arrow-left"></i> Voltar</a><br />
						</div>
					</div>
				</div>
				<div class="card-body">
					<h4 class="card-title text-muted mb-0">Filtre Pacientes</h4>
					<div class="pl-lg-0">
						<div class="row">
							<div class="col">
								<form asp-action="Index">
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="form-control-label" for="input-cpf">CPF/RG ou NOME</label>
												<input asp-for="Pesquisa" type="text" name="Pesquisa" class="form-control" placeholder="" />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-3">
											<div class="form-group">
												<label class="form-control-label" for="data-inicial"> Data Inicial</label>
												<input asp-for="DataInicial" type="date" id="data-inicial" name="DataInicial" class="form-control" />
											</div>
										</div>
										<div class="col-md-3">
											<div class="form-group">
												<label class="form-control-label" for="data-final"> Data Final</label>
												<input asp-for="DataFinal" type="date" id="data-final" name="DataFinal" class="form-control" />
											</div>
										</div>
									</div>

									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label class="form-control-label" for="input-virus-bacteria">Exame</label>
												@Html.DropDownListFor(model => model.VirusBacteria, ViewBag.VirusBacteria as SelectList, new
												{ @class = "form-control", @id = "input-virus-bacteria", @name = "VirusBacteria" })
											</div>
										</div>
									</div>

									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label class="form-control-label" for="input-atuacao-estado">Situacao</label>
												<select asp-for="Resultado" name="Resultado" class="form-control" id="input-resultado">
													<option>Todas as Opçoes</option>
													<option>Positivo</option>
													<option>Indeterminado</option>
													<option>Recuperado</option>
													<option>IgG/IgM Positivo</option>
													<option>Aguardando</option>
												</select>
											</div>
										</div>
									</div>

									<div class="col-md-0">
										<div class="row">
											<div class="col-md-3">
												<div class="form-group">
													<button type="submit" id="btn-filtar" class="form-control btn btn-default"><i class="fa fa-search"></i> Filtrar</button>
												</div>
											</div>
										</div>
									</div>
								</form>
							</div>
							<div class="col-md-4 text-center">
								<div class="table-responsive">
									<table class="table align-items-center table-flush">
										<thead class="thead-light">
											<tr>
												<th scope="col" class="sort" data-sort="resultado">
													PACIENTES
												</th>
												<th scope="col" class="sort" data-sort="total">
													Total
												</th>
											</tr>
										</thead>
										<tbody>
											<tr class="text-danger">
												<td>
													Positivos
												</td>
												<td>
													@Model.Positivos
												</td>
											</tr>
											<tr class="text-danger">
												<td>
													IgG/IgM Positivos
												</td>
												<td>
													@Model.IgGIgM
												</td>
											</tr>
											<tr class="text-warning">
												<td>
													Indeterminados
												</td>
												<td>
													@Model.Indeterminados
												</td>
											</tr>
											<tr class="text-blue">
												<td>
													Recuperados
												</td>
												<td>
													@Model.Recuperados
												</td>
											</tr>
											<tr class="text-success">
												<td>
													Aguardando Resultado
												</td>
												<td>
													@Model.Aguardando
												</td>
											</tr>
										</tbody>
									</table>
									<table class="table align-items-center table-flush">
										<thead class="thead-light">
											<tr>
												<th scope="col" class="sort" data-sort="resultado">
													Situação Paciente
												</th>
												<th scope="col" class="sort" data-sort="total">
													Total
												</th>
											</tr>
										</thead>
										<tbody>
											<tr class="text-danger">
												<td>
													UTI
												</td>
												<td>
													@Model.UTI
												</td>
											</tr>
											<tr class="text-warning">
												<td>
													Estabilização
												</td>
												<td>
													@Model.Estabilizacao
												</td>
											</tr>
											<tr class="text-warning">
												<td>
													Internamento Clinico
												</td>
												<td>
													@Model.Hospitalizado
												</td>
											</tr>
											<tr class="text-blue">
												<td>
													Isolamento
												</td>
												<td>
													@Model.Isolamento
												</td>
											</tr>
											<tr class="text-blue">
												<td>
													Recuperados
												</td>
												<td>
													@Model.Saudavel
												</td>
											</tr>
											<tr class="text-blue">
												<td>
													Óbitos
												</td>
												<td>
													@Model.Obito
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>

						</div>
					</div>
				</div>
				<div class="col-md-12 text-right">
					@using (Html.BeginForm("Export", "Exame", FormMethod.Post))
					{
						@for (int i = 0; i < Model.Exames.Count; i++)
						{
							<div class="form-group" hidden>
								<div class="col-md-10">
									@Html.EditorFor(model => Model.Exames[i].IdExame , new { htmlAttribu5tes = new { @class = "form-control" } })
								</div>
							</div>
						}
						<button type="submit" class="btn btn-success btn-xs"><i class="fa fa-list"></i> Exportar Planilha</button>
					}
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-custom align-items-center table-flush">
							<thead class="thead-light">
								<tr>
									<th scope="col" class="sort w10" data-sort="cpf">
										CPF/RG
									</th>
									<th scope="col" class="sort w26" data-sort="nome">
										Nome
									</th>
									<th scope="col" class="sort w5" data-sort="data-exame">
										Data <br> Exame
									</th>
									<th scope="col" class="sort w5 text-center" data-sort="ultima-situacao">
										Resultado
									</th>
									<th scope="col" class="sort w10 text-center" data-sort="data-monitoramento">
										Situação <br> Paciente
									</th>
									<th scope="col" class="sort w7 text-center" data-sort="data-monitoramento">
										Último <br> Monitoramento
									</th>
									<th scope="col" class="sort w20" data-sort="nome">
										Responsável <br> Monitoramento
									</th>
									<th class="w10">
									</th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model.Exames)
						{
									<tr>
										<td>
											<a href="#">@Html.DisplayFor(modelItem => item.Paciente.Cpf)</a>
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Paciente.Nome)
										</td>
										<th>
											@Html.DisplayFor(modelItem => item.DataExame)
										</th>
										<td class="text-center">
											@Html.DisplayFor(modelItem => item.UltimoResultado)
										</td>
										<td class="text-center">
											@Html.DisplayFor(modelItem => item.Paciente.SituacaoSaudeDescricao)
										</td>
										<td class="text-center">
											@if (item.DataUltimoMonitoramento.HasValue)
											{
												<div>@item.DataUltimoMonitoramento.Value.ToString("dd/MM/yyyy")</div>
											}
											else
											{
												@: -
											}
										</td>
										<th>
											@Html.DisplayFor(modelItem => item.Gestor.Nome)
										</th>
										<td>
											<a href="@Url.Action("Edit", "MonitorarPaciente", new { idPaciente = item.Paciente.Idpessoa, IdVirusBacteria = item.VirusBacteria.IdVirusBacteria })" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> Monitorar </a>
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
        </div>
    </div>
</div>

@if (TempData["mensagemAviso"] != null)
{
    <div id="mensagem-retorno" onclick="swtAlertRedirectIndex('warning','Aviso', '@TempData["mensagemAviso"]','/Home/Index')"></div>
}


@section Scripts {
    <script>
        $(document).ready(function () {
            if (document.querySelector('#mensagem-retorno'))
                document.getElementById("mensagem-retorno").click();
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="~/assets/js/sweet-alert.js"></script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}