MonitoraSUS/Controllers/EmpresaExameController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Model;
using Util;
using Service.Interface;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace MonitoraSUS.Controllers
{
    [Authorize(Roles = "SECRETARIO, ADM")]
    public class EmpresaExameController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IEmpresaExameService _empresaContext;
        private readonly IExameService _exameContext;
        private readonly IPessoaService _pessoaContext;
        private readonly IPessoaTrabalhaEstadoService _trabalhaEstadoContext;
        private readonly IPessoaTrabalhaMunicipioService _trabalhaMunicipioContext;
        private readonly IEstadoService _estadoContext;
        private readonly IMunicipioService _municipioContext;
		private readonly IUsuarioService _usuarioContext;

		public EmpresaExameController(IConfiguration configuration,
                                      IEmpresaExameService empresaContext,
                                      IExameService exameContext,
                                      IPessoaService pessoaContext,
                                      IPessoaTrabalhaEstadoService trabalhaEstadoContext,
                                      IPessoaTrabalhaMunicipioService trabalhaMunicipioContext,
                                      IEstadoService estadoContext,
                                      IMunicipioService municipioContext,
									  IUsuarioService usuarioContext)
        {
            _configuration = configuration;
            _empresaContext = empresaContext;
            _exameContext = exameContext;
            _pessoaContext = pessoaContext;
            _trabalhaEstadoContext = trabalhaEstadoContext;
            _trabalhaMunicipioContext = trabalhaMunicipioContext;
            _estadoContext = estadoContext;
            _municipioContext = municipioContext;
			_usuarioContext = usuarioContext;
        }

        public IActionResult Index()
        {
            return View(GetAllEmpresas());
        }

        public List<EmpresaExameModel> GetAllEmpresas()
        {
            var usuario = _usuarioContext.RetornLoggedUser((ClaimsIdentity)User.Identity);
            var pessoa = _pessoaContext.GetById(usuario.UsuarioModel.IdPessoa);
            var empresas = new List<EmpresaExameModel>();
            if (usuario.RoleUsuario.Equals("SECRETARIO") || usuario.RoleUsuario.Equals("ADM"))
            {

                var trabalhaEstado = _trabalhaEstadoContext.GetByIdPessoa(pessoa.Idpessoa);
                if (trabalhaEstado != null)
                {
                    if (trabalhaEstado.IdEmpresaExame != EmpresaExameModel.EMPRESA_ESTADO_MUNICIPIO)
                        empresas = new List<EmpresaExameModel>() { _empresaContext.GetById(trabalhaEstado.IdEmpresaExame) };
                    else
                    {
                        var estado = _estadoContext.GetById(trabalhaEstado.IdEstado);
                        empresas = _empresaContext.GetByUF(estado.Uf);
                    }
                }
                else
                {
                    var trabalhaMunicipio = _trabalhaMunicipioContext.GetByIdPessoa(pessoa.Idpessoa);
                    if (trabalhaMunicipio != null)
                    {
                        var municipio = _municipioContext.GetById(trabalhaMunicipio.IdMunicipio);
                        var estado = _estadoContext.GetById(int.Parse(municipio.Uf));
                        empresas = _empresaContext.GetByUF(estado.Uf);
                    }
                }
            }
            return empresas;
        }

        public IActionResult Details(int id)
        {
            return View(_empresaContext.GetById(id));
        }

        public IActionResult Create()
        {
            ViewBag.googleKey = _configuration["GOOGLE_KEY"];
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmpresaExameModel empresa)
        {
            ViewBag.googleKey = _configuration["GOOGLE_KEY"];

			if (Methods.ValidarCnpj(empresa.Cnpj))
            {
				if (VerificaQtdLeitos(empresa) == 1)
                {
                    TempData["MensagemErro"] = "A quantidade de leitos disponíveis não pode ser menor do que " +
                                               "a quantidade total de leitos!";
                    return View(empresa);
                }
                else if (VerificaQtdLeitos(empresa) == 2)
                {
                    TempData["MensagemErro"] = "A quantidade de leitos não pode ser um valor menor que zero!";
                    return View(empresa);
                }

                empresa = RemoveCaracteresEspeciais(empresa);
                if (_empresaContext.GetByCnpj(empresa.Cnpj).Count == 0)
                {
                    try
                    {
                        _empresaContext.Insert(empresa);
                    }
                    catch
                    {
                        TempData["MensagemErro"] = "Algo deu errado, tente novamente.";
                        return View(empresa);
                    }

                    TempData["MensagemSucesso"] = "Organização Cadastrada com sucesso!";
                    return View();
                }
                else
                {
                    TempData["MensagemCnpj"] = "Já existe uma empresa com este CNPJ.";
                    return View(empresa);
                }

            }
            else
            {
                TempData["MensagemCnpj"] = "Esse CNPJ não é válido.";
                return View(empresa);
            }
        }

        public IActionResult Edit(int id)
        {
            ViewBag.googleKey = _configuration["GOOGLE_KEY"];
            return View(_empresaContext.GetById(id));
        }

        /// <summary>
        /// Edita um exame existente da base de dados
        /// </summary>
        /// <param name="exame"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EmpresaExameModel empresa)
        {
            ViewBag.googleKey = _configuration["GOOGLE_KEY"];

            if (Methods.ValidarCnpj(empresa.Cnpj))
            {
                empresa = RemoveCaracteresEspeciais(empresa);
                if (_empresaContext.GetById(empresa.Id) != null)
                {

                    if (VerificaQtdLeitos(empresa) == 1)
                    {
                        TempData["MensagemErro"] = "A quantidade de leitos disponíveis não pode ser menor do que " +
                                                   "a quantidade total de leitos!";
                        return View(empresa);
                    }
                    else if (VerificaQtdLeitos(empresa) == 2)
                    {
                        TempData["MensagemErro"] = "A quantidade de leitos não pode ser um valor menor que zero!";
                        return View(empresa);
                    }

                    try
                    {
                        _empresaContext.Update(empresa);
                    }
                    catch
                    {
                        TempData["MensagemErro"] = "Algo deu errado, tente novamente.";
                        return View(empresa);
                    }

                    TempData["MensagemSucesso"] = "Atualização feita com sucesso!";
                    return View();
                }
                else
                {
                    TempData["MensagemCnpj"] = "Já existe uma empresa com este CNPJ.";
                    return View(empresa);
                }

            }
            else
            {
                TempData["MensagemCnpj"] = "Esse CNPJ não é válido.";
                return View(empresa);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            var exames = _exameContext.GetByIdEmpresa(id, DateTime.MinValue, DateTime.MaxValue);
            var pessoaEstado = _trabalhaEstadoContext.GetByIdEmpresa(id);

            try
            {
                if (exames == null && pessoaEstado == null)
                {
                    _empresaContext.Delete(id);
                    TempData["mensagemSucesso"] = "Laboratório removido com sucesso!";
                }
                else
                {
                    TempData["mensagemErro"] = "Esse laboratório não pode ser removido pois existem " +
                                                  "profissionais e exames cadastrados que dependem dele!";
                }


            }
            catch
            {
                TempData["mensagemErro"] = "Houve um problema ao remover laboratório, tente novamente!";
            }

            return RedirectToAction(nameof(Index));
        }

        public int VerificaQtdLeitos(EmpresaExameModel empresa)
        {
            var status = 0;
            if (empresa.PossuiLeitosInternacao)
            {
                if (empresa.NumeroLeitosDisponivel > empresa.NumeroLeitos)
                    status = 1;

                if (empresa.NumeroLeitosUtidisponivel > empresa.NumeroLeitosUti)
                    status = 1;

                if (empresa.NumeroLeitosDisponivel < 0 || empresa.NumeroLeitos < 0 ||
                    empresa.NumeroLeitosUtidisponivel < 0 || empresa.NumeroLeitosUti < 0)
                    status = 2;
            }

            return status;
        }


        public EmpresaExameModel RemoveCaracteresEspeciais(EmpresaExameModel empresa)
        {
            empresa.Cep = Methods.RemoveSpecialsCaracts(empresa.Cep);
            empresa.FoneCelular = Methods.RemoveSpecialsCaracts(empresa.FoneCelular);

MonitoraSUS/Views/EmpresaExame/Details.cshtml
@model Model.EmpresaExameModel

@{
    ViewData["Title"] = "Details";
}

<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-content">
                <div class="card-header bg-transparent">
                    <div class="row align-items-center">

                        <div class="col">
                            <h5 class="card-title text-muted mb-0">MonitoraSUS</h5>
                            <h5 class="h3 mb-0">Laboratório</h5>
                        </div>
                        <div class="col text-right">
                            <!--a class="btn btn-success" asp-action="Create">Novo Exame</!--a-->
                            <a class="btn btn-default" asp-controller="Home" asp-action="Index"> <i class="fas fa-arrow-left"></i> Voltar</a><br />
                        </div>

                    </div>
                    <hr />

                    <div>
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Id)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Id)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Cnpj)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Cnpj)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Nome)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Nome)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Cep)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Cep)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Rua)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Rua)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Bairro)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Bairro)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Cidade)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Cidade)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Estado)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Estado)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Numero)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Numero)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Complemento)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Complemento)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.FoneCelular)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.FoneCelular)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.FoneFixo)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.FoneFixo)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.Email)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.Email)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.EmiteLaudoExame)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.EmiteLaudoExame)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.PossuiLeitosInternacao)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.PossuiLeitosInternacao)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.NumeroLeitos)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.NumeroLeitos)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.NumeroLeitosDisponivel)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.NumeroLeitosDisponivel)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.NumeroLeitosUti)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.NumeroLeitosUti)
                            </dd>
                            <dt>
                                @Html.DisplayNameFor(model => model.NumeroLeitosUtidisponivel)
                            </dt>
                            <dd>
                                @Html.DisplayFor(model => model.NumeroLeitosUtidisponivel)
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MonitoraSUS/Views/EmpresaExame/Index.cshtml
@model IEnumerable<Model.EmpresaExameModel>
@using System.Security.Claims;

@{
	ViewData["Title"] = "Index";
	//var usuario = Methods.RetornLoggedUser((ClaimsIdentity)User.Identity);
}

<div class="container-fluid mt--6">
	<div class="row">
		<div class="col-md-12">
			<div class="card card-content">
				<div class="card-header bg-transparent">
					<div class="row align-items-center">

						<div class="col">
							<h5 class="card-title text-muted mb-0">MonitoraSUS</h5>
							<h5 class="h3 mb-0">Cadasto de Hospitais/Laboratórios</h5>
						</div>
						<div class="col text-right">
							<a class="btn btn-success" asp-controller="EmpresaExame" asp-action="Create">Novo</a>
							<a class="btn btn-default" asp-controller="Home" asp-action="Index"> <i class="fas fa-arrow-left"></i> Voltar</a><br />
						</div>

					</div>
					<hr />
					<div class="card-body ">
						<div class="table-responsive">
							<table class="table align-items-center table-flush">
								<thead class="thead-light">
									<tr>
										<th scope="col" class="sort" data-sort="cnpj">
											@Html.DisplayNameFor(model => model.Cnpj)
										</th>
										<th scope="col" class="sort" data-sort="nome">
											@Html.DisplayNameFor(model => model.Nome)
										</th>
										<th scope="col" class="sort" data-sort="celular">
											@Html.DisplayNameFor(model => model.FoneCelular)
										</th>
										<th scope="col" class="sort" data-sort="email">
											@Html.DisplayNameFor(model => model.Email)
										</th>
										<th></th>
									</tr>
								</thead>
								<tbody class="list">
									@foreach (var item in Model)
									{
										<tr>
											<td>
												<a href="#">@Html.DisplayFor(modelItem => item.Cnpj)</a>
											</td>
											<td>
												@Html.DisplayFor(modelItem => item.Nome)
											</td>
											<td>
												@Html.DisplayFor(modelItem => item.FoneCelular)
											</td>
											<td>
												@if (item.Email == null)
												{
													<div> - </div>
												}
												else
												{
													@Html.DisplayFor(modelItem => item.Email)
												}
											</td>
											<td>
												<a href="@Url.Action("Details", "EmpresaExame", new { id = item.Id})" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> Detalhes </a>
												<a href="@Url.Action("Edit", "EmpresaExame", new { id = item.Id })" class="btn btn-info btn-xs"><i class="fa fa-edit"></i> Editar </a>
												<a data-toggle="modal" data-target="#modal-confirmar-@item.Id" class="btn btn-danger btn-xs text-white"><i class="fa fa-trash "></i> Remover </a>
												<div class="modal fade bs-example-modal-sm" id="modal-confirmar-@item.Id" tabindex="-1" role="dialog" aria-hidden="true">
													<div class="modal-dialog modal-sm">
														<div class="modal-content text-center" style="padding: 10pt">
															<h4> Confirmar Remoção da organização ? </h4>

															<p class="text-left">
																<h4>CNPJ</h4> @item.Cnpj <br />
																<h4>Laboratório</h4> @item.Nome <br />
															</p>

															@using (Html.BeginForm("Delete", "EmpresaExame", new { id = item.Id }, FormMethod.Post))
															{
																<a class="btn btn-danger text-white" data-dismiss="modal">Cancelar</a>
																<button type="submit" value="Remover" class="btn btn-success btn-xs">Confimar</button>
															}
														</div>
													</div>
												</div>
											</td>
										</tr>
									}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


@if (TempData["mensagemErro"] != null || TempData["mensagemSucesso"] != null)
{
	<div class="modal fade bs-example-modal-sm" id="modal-mensagem-retorno" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog modal-sm">
			<div class="modal-content" style="padding: 10pt">
				<div class="text-center">
					<br />
					@if (TempData["mensagemErro"] != null)
					{
						<p>@TempData["mensagemErro"]</p>
					}
					else
					{
						<p>@TempData["mensagemSucesso"]</p>
					}

					<button data-dismiss="modal" class="btn btn-success">Ok</button>
				</div>
			</div>
		</div>
	</div>
}

<script>

	window.onload = function () { }
	if (document.querySelector('#modal-mensagem-retorno')) {
		$('#modal-mensagem-retorno').modal('show');
	}
	};
</script>